services:

    prometheus:
        container_name: prometheus
        image: prom/prometheus
        networks:
            - m169_network
        volumes:
            - ./prometheus:/etc/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        ports:
            - 9090:9090
        restart: always

    grafana:
        container_name: grafana
        image: grafana/grafana
        networks:
            - m169_network
        ports:
          - 3000:3000
        depends_on:
          - prometheus




###################################################



    reverseproxy:
        image: reverseproxy
        container_name: reverseproxy
        networks:
            - m169_network
        ports:
            - 80:80
        restart: always
    nginx:
        container_name: server-nginx
        depends_on:
            - reverseproxy
        image: server-nginx
        networks:
            - m169_network

        restart: always

    apache:
        container_name: server-apache
        depends_on:
            - reverseproxy
        image: server-apache
        networks:
            - m169_network
        restart: always
networks:
  m169_network:
    name: m169_network
