services:
    reverseproxy:
        image: kujo01243/reverseproxy
        ports:
            - 80:80
        restart: always

    nginx:
        depends_on:
            - reverseproxy
        image: kujo01243/server-nginx
        restart: always

    apache:
        depends_on:
            - reverseproxy
        image: kujo01243/server-apache
        restart: always
