services:

    prometheus:
        container_name: prometheus
        depends_on:
            - reverseproxy
        image: ghcr.io/kujo01243/m169-prometheus:v1
        networks:
            - m169_network
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        restart: always

    grafana:
        container_name: grafana
        image: ghcr.io/kujo01243/m169-grafana:v1
        networks:
            - m169_network
        depends_on:
          - prometheus
        environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=Passwort123
        - GF_INSTALL_PLUGINS=grafana-piechart-panel

    reverseproxy:
        image: ghcr.io/kujo01243/m169-reverseproxy:v1
        container_name: reverseproxy
        networks:
            - m169_network
        ports:
            - 80:80
        restart: always
    server-nginx:
        container_name: server-nginx
        depends_on:
            - reverseproxy
        image: ghcr.io/kujo01243/m169-server-nginx:v1
        networks:
            - m169_network
        ports:
            - 9112:9112
        restart: always

    server-apache:
        container_name: server-apache
        depends_on:
            - reverseproxy
        image: ghcr.io/kujo01243/m169-server-apache:v1
        networks:
            - m169_network
        restart: always
    
    monitoring-server-nginx:
        container_name: monitoring-server-nginx
        depends_on:
            - server-nginx
            - reverseproxy
        image: nginx/nginx-prometheus-exporter
        command: [ "-nginx.scrape-uri=http://server-nginx:9112/metrics" ]
        networks:
            - m169_network
        restart: always
    monitoring-reverseproxy:
        container_name: monitoring-reverseproxy
        depends_on:
            - reverseproxy
        image: nginx/nginx-prometheus-exporter
        command: [ "-nginx.scrape-uri=http://reverseproxy:9112/metrics" ]
        networks:
            - m169_network
        restart: always
    monitoring-server-apache:
        container_name: monitoring-server-apache
        depends_on:
            - reverseproxy
            - server-apache
        image: previousnext/apache-exporter
        environment:
        - APACHE_STATUS_URL=http://server-apache:80/metrics
        networks:
            - m169_network

networks:
  m169_network:
    name: m169_network
