services:
    reverseproxy:
        image: reverseproxy
        ports:
            - 80:80
        restart: always

    nginx:
        depends_on:
            - reverseproxy
        image: server-nginx
        restart: always

    apache:
        depends_on:
            - reverseproxy
        image: server-apache
        restart: always
