version: '3'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/root/praktikum/prometheus/prometheus'
    depends_on:
      - 
      - webserver2
    networks:
      - m169_network
