global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'ueberwachung-webserver'
    metrics_path: /metrics
    static_configs:
      - targets: ['monitoring-server-nginx:9113', 'monitoring-reverseproxy:9113','monitoring-server-apache:9117']


