global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'webserver1'
    static_configs:
      - targets: ['<IP_Webserver1>:80']

  - job_name: 'webserver2'
    static_configs:
      - targets: ['<IP_Webserver2>:80']

